### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by johannpayer** [djanidaud/compound-parser#1]
Hello, thanks for the wonderful library. I'm trying to use it with TypeScript, but the package doesn't appear to have any TypeScript definitions. If you would like, I can solve this issue, but I need write access to push my branch. Please let me know if you're interested.

**Comment by djanidaud** [comment]
@johannpayer Thanks for the help! I added you to the list of collaborators and I think you should be authorized now.

**Comment by johannpayer** [comment]
@djanidaud You're welcome. I've linked my pull request above. Feel free to merge if it looks good.
